### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by EMQcarlos** [lhkbob/eve-swagger-js#17]
This might be a problem because of an outdated node js version on aws lambda (4.3.2)

> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/eve_swagger_interface/src/index.js:1:75)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

**Comment by lhkbob** [comment]
With the 0.2 release I switched to ES6.  I am using node 6.9.1.  It should be possible to transpile it to older versions of JS with babel, but I haven't automated that.  Is that something you can just do on your end?

**Comment by ex1tium** [comment]
I upgraded my node from v4.6.1 to v6.9.5 and after that I'm getting a lot of different errors. My guess is some of the packages I use do not support v6.9.5 :(

```
module.js:471
    throw err;
    ^

Error: Cannot find module '../internal/Names'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/eve_swagger_interface/src/api/Alliances.js:4:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/eve_swagger_interface/src/Api.js:22:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/eve_swagger_interface/src/index.js:1:75)
    at Module._compile (module.js:570:32)


Process exited with code: 1
```

Part of my package.json

```
  "dependencies": {
    "body-parser": "~1.16.0",
    "config": "^1.25.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.0",
    "ejs": "^2.5.6",
    "express": "^4.14.1",
    "express-session": "^1.15.1",
    "mongoose": "^4.8.2",
    "mongoose-findorcreate": "^1.0.0",
    "morgan": "~1.7.0",
    "passport": "^0.3.2",
    "passport-eve": "^1.0.2",
    "request": "^2.79.0",
    "serve-favicon": "~2.3.2",
    "eve_swagger_interface": "git://github.com/lhkbob/eve-swagger-js.git#0.2.1"
  },
```

Any chance you could maintain a version compatible with Node 4 versions

**Comment by lhkbob** [comment]
I accepted a pull request the other day fixing this but haven't put out a new release yet. Turns out my filesystem is case insensitive so it didn't affect me. 

If you depend on the latest instead of using a version tag it'll be fine. Although I also need to update to the latest ESI version so once that's done I'll do a proper release.

**Comment by lhkbob** [comment]
I have not yet decided how to distribute a transpiled version for older engines. Most backend things should be able to run with a version of node that supports es6. On the other hand babel is pretty easy to setup and then it's just a matter of pushing two versions instead of one for a release.

**Comment by lhkbob** [comment]
Just merged, and will push a new release soon for it, but babel now converts the ES6 code to target node v4, which should help in these situations. PR #31
