### ISSUE TITLE
esi.types(type_id).info() not found

### ISSUE THREAD

**Issue by cmcintosh** [lhkbob/eve-swagger-js#75]
Using this to look at building a trade hub similar to Eve Central, running into a bit of a issue, not sure if i am just calling something wrong, but cant seem to get info For Types.

**Comment by lhkbob** [comment]
What version are you using? The 0.3.3 npm Jacascript release, or the TypeScript update that is roughed out in the master branch (but not released yet).

If you’re not sure, does your node_module download contain a tsconfig.json file?

I’ll look into this for sure though.

**Comment by cmcintosh** [comment]
Actually, i think i did not have enough coffee.   I was running types.all() to try and build a cache of the items for use in the app, the first returned result 0, was causing a issiue in the .info funciton.

Full error:
'''
Unhandled rejection TypeError: esi.types(...).info is not a function
    at /Users/cmcintosh/Documents/Games/EveTrader/controller/ItemsController.js:25:13
    at tryCatcher (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/cmcintosh/Documents/Games/EveTrader/node_modules/bluebird/js/release/async.js:143:10)
'''

**Comment by lhkbob** [comment]
Also is the error that the info or types function is undefined, or is it that it’s throwing an error because the specific type id is not found?

**Comment by cmcintosh** [comment]
I think its the latter, meaning it did a call and could not find the type id so threw an error.

**Comment by lhkbob** [comment]
I figured it out, it is a bug in the esi.types callable instance.  It looks at the value passed in for truthiness, and if truthy returns a Type instance (e.g. behaves like esi.types.get(id)), and if falsey it behaves like esi.types.all().

In the case where you pass 0 as the id, that breaks the current code.  Using truthiness was a mistake in this case and should have checked if it was undefined explicitly.  When you call esi.types(0), you're actually calling esi.types.all() and receiving a Promise, which won't have the info() function on it.

If you explicitly use esi.types.get(id), you will get around this issue for the time being.

Keep in mind that I am in the process of updating to TypeScript for the 0.4 release.  This will keep the API largely the same and should automatically address this truthy vs. undefined issue.  Once released, it will still be usable by JavaScript code so it won't force you to update or anything.

Hope that helps!

**Comment by cmcintosh** [comment]
No problem I appreciate the library.  Makes building things around it a bit easier.
